name: jsdoc-workflow

on:
  # Triggers the workflow on push events but only for the main or dev branch
  push:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Set up workspace
        uses: actions/checkout@v2

      - name: Build documention
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          output_dir: ./doc
          config_file: conf.json
          template: minami
          front_page: README.md

      - name: Auto commit
        run: |
          git add .
          git -c user.name='jsdoc-bot' -c user.email='speed-highlight@protonmail.com' commit -m "Doc update" || exit 0
          git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
