name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up workspace
        run: |
          cd ${GITHUB_WORKSPACE}
          git clone https://github.com/${{ github.repository }}.git .

      - name: Auto minify
        run: |
          chmod +x ./.github/workflows/minify.bash
          ./.github/workflows/minify.bash
      - name: Auto commit
        run: |
          git add .
          git -c user.name='minify-bot' -c user.email='speed-highlight@protonmail.com' commit -m "Auto minify" || exit 0
          git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
