name: npm-pkg-workflow

on:
  # Triggers the workflow on new release publish
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up workspace
        run: |
          cd ${GITHUB_WORKSPACE}
          git clone https://github.com/${{ github.repository }}.git . -b ${GITHUB_REF#refs/heads/}

      - name: Set up npm
        run: |
          apt install npm
          
      - name: Publish to npm
        run: |
          npm config set registry https://registry.npmjs.org/
          npm set //https://registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm publish --access public --tag ${{ github.event.release.tag_name }}

      - name: Publish to github packages
        run: |
          npm config set registry https://npm.pkg.github.com/
          npm set //https://npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm publish --access public --tag ${{ github.event.release.tag_name }}

      - name: Auto commit
        run: |
          git add .
          git -c user.name='npm-pkg-bot' -c user.email='speed-highlight@protonmail.com' commit -m "Npm upgrade version"
          git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
