name: npm-pkg-workflow

on:
  # Triggers the workflow on new release
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
        matrix:
         node-version: [16.x]

    permissions:
      contents: write
      packages: write

    steps:
      - name: Set up workspace
        run: |
          cd ${GITHUB_WORKSPACE}
          git clone https://github.com/${{ github.repository }}.git .

      - name: Create new npm version
        run: |
          npm version --no-git-tag-version ${{ github.event.release.tag_name }}
          git add package.json
          git -c user.name='npm-pkg-bot' -c user.email='speed-highlight@protonmail.com' commit -m "[npm-pkg-bot] updated package.json to version ${{ github.event.release.tag_name }}"

      - name: Publish to npm
        run: |
          npm set registry http://registry.npmjs.org/
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm publish --access public

      - name: Publish to github pkg
        run: |
          npm set registry http://npm.pkg.github.com/
          npm config set //npm.pkg.github.com//:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm publish --access public
