name: npm-pkg-workflow

on:
  # Triggers the workflow on new release
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write
      packages: write

    steps:
      - name: Set up workspace
        run: |
          cd ${GITHUB_WORKSPACE}
          git clone https://github.com/${{ github.repository }}.git .

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          scope: '@speed-highlight'

      - name: Create new npm version
        run: |
          npm version --no-git-tag-version ${{ github.event.release.tag_name }}
          git add package.json
          git -c user.name='npm-pkg-bot' -c user.email='speed-highlight@protonmail.com' commit -m "[npm-pkg-bot] updated package.json to version ${{ github.event.release.tag_name }}"

      - name: Publish to npm
        run: |
          npm publish --access public --registry https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to github pkg
        run: |
          npm publish --access public --registry https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
