name: npm-pkg-workflow

on:
  # Triggers the workflow on new release
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Create new npm version
        run: |
          npm version --no-git-tag-version ${{ github.event.release.tag_name }}
          git add package.json
          git -c user.name='npm-pkg-bot' -c user.email='speed-highlight@protonmail.com' commit -m "[npm-pkg-bot] updated package.json to version ${{ github.event.release.tag_name }}"

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: '@speed-highlight'

      - name: Publish to npm
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@speed-highlight'

      - name: Publish to github pkg
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push new version to github
        run: |
          git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
